use std::sync::{
    Arc, Mutex,
    atomic::{AtomicBool, Ordering},
};
use tauri::{Monitor, PhysicalPosition, PhysicalSize, WebviewWindow, WindowEvent};

#[derive(Clone, PartialEq)]
struct MonitorArea {
    origin: PhysicalPosition<i32>,
    size: PhysicalSize<u32>,
    scale: f64,
}

impl From<Monitor> for MonitorArea {
    fn from(monitor: Monitor) -> Self {
        Self {
            origin: monitor.work_area().position,
            size: monitor.work_area().size,
            scale: monitor.scale_factor(),
        }
    }
}

fn minimum_size(available: PhysicalSize<u32>, scale: f64) -> PhysicalSize<u32> {
    PhysicalSize::new(
        (900.0 * scale).round().min(available.width as f64) as u32,
        (640.0 * scale).round().min(available.height as f64) as u32,
    )
}

fn restore_geometry(
    origin: PhysicalPosition<i32>,
    available: PhysicalSize<u32>,
    scale: f64,
) -> (PhysicalPosition<i32>, PhysicalSize<u32>, PhysicalSize<u32>) {
    let minimum = minimum_size(available, scale);
    let size = PhysicalSize::new(
        ((available.width as f64 * 0.85).round() as u32).max(minimum.width),
        ((available.height as f64 * 0.85).round() as u32).max(minimum.height),
    );
    let position = PhysicalPosition::new(
        origin.x + ((available.width - size.width) / 2) as i32,
        origin.y + ((available.height - size.height) / 2) as i32,
    );
    (position, size, minimum)
}

pub fn restore_to_monitor(window: &WebviewWindow) -> Result<(), String> {
    let monitor = window
        .current_monitor()
        .map_err(|e| e.to_string())?
        .ok_or("无法获取当前显示器的可用区域")?;
    let area = monitor.work_area();
    let (position, size, minimum) =
        restore_geometry(area.position, area.size, monitor.scale_factor());
    window.unmaximize().map_err(|e| e.to_string())?;
    apply_geometry(window, position, size, minimum)
}

fn apply_geometry(
    window: &WebviewWindow,
    position: PhysicalPosition<i32>,
    size: PhysicalSize<u32>,
    minimum: PhysicalSize<u32>,
) -> Result<(), String> {
    // Tauri sizes the client area; Windows keeps resize borders even without decorations.
    let outer = window.outer_size().map_err(|e| e.to_string())?;
    let inner = window.inner_size().map_err(|e| e.to_string())?;
    let border_width = outer.width.saturating_sub(inner.width);
    let border_height = outer.height.saturating_sub(inner.height);
    window
        .set_min_size(Some(PhysicalSize::new(
            minimum.width.saturating_sub(border_width),
            minimum.height.saturating_sub(border_height),
        )))
        .map_err(|e| e.to_string())?;
    window
        .set_size(PhysicalSize::new(
            size.width.saturating_sub(border_width),
            size.height.saturating_sub(border_height),
        ))
        .map_err(|e| e.to_string())?;
    window.set_position(position).map_err(|e| e.to_string())?;
    Ok(())
}

fn fit_to_monitor(
    area: &MonitorArea,
    position: PhysicalPosition<i32>,
    size: PhysicalSize<u32>,
) -> (PhysicalPosition<i32>, PhysicalSize<u32>, PhysicalSize<u32>) {
    let minimum = minimum_size(area.size, area.scale);
    let size = PhysicalSize::new(
        size.width.clamp(minimum.width, area.size.width),
        size.height.clamp(minimum.height, area.size.height),
    );
    let position = PhysicalPosition::new(
        position.x.clamp(
            area.origin.x,
            area.origin.x + (area.size.width - size.width) as i32,
        ),
        position.y.clamp(
            area.origin.y,
            area.origin.y + (area.size.height - size.height) as i32,
        ),
    );
    (position, size, minimum)
}

pub fn watch_monitor_changes(window: &WebviewWindow) -> Result<(), String> {
    let initial: MonitorArea = window
        .current_monitor()
        .map_err(|e| e.to_string())?
        .ok_or("无法获取当前显示器的可用区域")?
        .into();
    let state = Arc::new(MonitorWatch {
        last_area: Mutex::new(initial),
        queued: AtomicBool::new(false),
        closed: AtomicBool::new(false),
    });
    let watched = window.clone();
    window.on_window_event(move |event| {
        if matches!(event, WindowEvent::Destroyed) {
            state.closed.store(true, Ordering::SeqCst);
            return;
        }
        if !matches!(
            event,
            WindowEvent::Moved(_)
                | WindowEvent::Resized(_)
                | WindowEvent::ScaleFactorChanged { .. }
        ) || state.closed.load(Ordering::SeqCst)
            || state.queued.swap(true, Ordering::SeqCst)
        {
            return;
        }
        let window = watched.clone();
        let state = state.clone();
        // Defer beyond WM_DPICHANGED so Windows/Tao finishes its own DPI resize first.
        // Coalesce native move/resize events and ignore those generated by our correction.
        tauri::async_runtime::spawn(async move {
            let target = window.clone();
            let pending = state.clone();
            if let Err(error) = window.run_on_main_thread(move || {
                if let Err(error) = pending.refresh(&target) {
                    eprintln!("更新窗口显示器约束失败：{error}");
                }
                pending.queued.store(false, Ordering::SeqCst);
            }) {
                state.queued.store(false, Ordering::SeqCst);
                eprintln!("调度窗口显示器检查失败：{error}");
            }
        });
    });
    Ok(())
}

struct MonitorWatch {
    last_area: Mutex<MonitorArea>,
    queued: AtomicBool,
    closed: AtomicBool,
}

impl MonitorWatch {
    fn refresh(&self, window: &WebviewWindow) -> Result<(), String> {
        // Setting minimum size restores a maximized Tao window. Defer until
        // it becomes a normal window, keeping the old area as a pending change.
        if self.closed.load(Ordering::SeqCst)
            || window.is_maximized().map_err(|e| e.to_string())?
            || window.is_minimized().map_err(|e| e.to_string())?
        {
            return Ok(());
        }
        let area: MonitorArea = window
            .current_monitor()
            .map_err(|e| e.to_string())?
            .ok_or("无法获取当前显示器的可用区域")?
            .into();
        if *self.last_area.lock().unwrap() == area {
            return Ok(());
        }
        let (position, size, minimum) = fit_to_monitor(
            &area,
            window.outer_position().map_err(|e| e.to_string())?,
            window.outer_size().map_err(|e| e.to_string())?,
        );
        apply_geometry(window, position, size, minimum)?;
        *self.last_area.lock().unwrap() = area;
        Ok(())
    }
}

#[tauri::command]
pub fn toggle_window_maximized(window: WebviewWindow) -> Result<(), String> {
    if window.is_maximized().map_err(|e| e.to_string())? {
        restore_to_monitor(&window)
    } else {
        window.maximize().map_err(|e| e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn high_to_low_dpi_replaces_old_minimum_and_fits_the_smaller_screen() {
        let old_minimum = minimum_size(PhysicalSize::new(2560, 1528), 1.5);
        let area = MonitorArea {
            origin: PhysicalPosition::new(-1280, 0),
            size: PhysicalSize::new(1280, 680),
            scale: 1.0,
        };
        let (position, size, minimum) = fit_to_monitor(
            &area,
            PhysicalPosition::new(-1100, 100),
            PhysicalSize::new(1800, 1100),
        );
        assert_eq!(old_minimum, PhysicalSize::new(1350, 960));
        assert_eq!(minimum, PhysicalSize::new(900, 640));
        assert_eq!(size, area.size);
        assert_eq!(position, area.origin);
        // Resizing to the new screen's logical minimum is now possible.
        assert_eq!(fit_to_monitor(&area, position, minimum).1, minimum);
    }

    #[test]
    fn low_to_high_dpi_recomputes_minimum_without_resetting_to_eighty_five_percent() {
        let area = MonitorArea {
            origin: PhysicalPosition::new(1920, 40),
            size: PhysicalSize::new(2560, 1520),
            scale: 1.5,
        };
        let position = PhysicalPosition::new(2000, 100);
        let manual = PhysicalSize::new(1600, 1100);
        let (fitted_position, size, minimum) = fit_to_monitor(&area, position, manual);
        assert_eq!(minimum, PhysicalSize::new(1350, 960));
        assert_eq!((fitted_position, size), (position, manual));
        assert_eq!(
            fit_to_monitor(&area, position, PhysicalSize::new(900, 640)).1,
            minimum
        );
    }

    #[test]
    fn same_dpi_smaller_work_area_clamps_only_overflow_and_caps_minimum() {
        let area = MonitorArea {
            origin: PhysicalPosition::new(0, 40),
            size: PhysicalSize::new(800, 560),
            scale: 1.5,
        };
        let (position, size, minimum) = fit_to_monitor(
            &area,
            PhysicalPosition::new(100, -20),
            PhysicalSize::new(1100, 800),
        );
        assert_eq!(
            (position, size, minimum),
            (area.origin, area.size, area.size)
        );
        let other = MonitorArea {
            origin: PhysicalPosition::new(800, 40),
            ..area.clone()
        };
        assert!(area != other);
        let rescaled = MonitorArea {
            scale: 1.0,
            ..area.clone()
        };
        assert!(area != rescaled);
    }

    #[test]
    fn centers_in_work_area_including_negative_monitor_origins() {
        let (position, size, minimum) = restore_geometry(
            PhysicalPosition::new(-1920, 40),
            PhysicalSize::new(1920, 1040),
            1.0,
        );
        assert_eq!(size, PhysicalSize::new(1632, 884));
        assert_eq!(position, PhysicalPosition::new(-1776, 118));
        assert_eq!(minimum, PhysicalSize::new(900, 640));
    }

    #[test]
    fn respects_dpi_minimum_without_exceeding_small_work_areas() {
        for (width, height, scale) in [
            (1920, 1040, 1.25),
            (1920, 1040, 1.5),
            (1280, 680, 1.5),
            (800, 560, 1.0),
            (1440, 900, 1.0),
            (1280, 780, 1.0),
            (1024, 720, 1.0),
            (900, 700, 1.0),
        ] {
            let (position, size, minimum) = restore_geometry(
                PhysicalPosition::new(0, 0),
                PhysicalSize::new(width, height),
                scale,
            );
            assert!(size.width <= width && size.height <= height);
            assert!(size.width >= minimum.width && size.height >= minimum.height);
            assert!((position.x * 2 + size.width as i32 - width as i32).abs() <= 1);
            assert!((position.y * 2 + size.height as i32 - height as i32).abs() <= 1);
        }
        let (_, size, _) = restore_geometry(
            PhysicalPosition::new(0, 0),
            PhysicalSize::new(1280, 680),
            1.5,
        );
        assert_eq!(size, PhysicalSize::new(1280, 680));
    }
}
